from __future__ import annotations

"""Generate the human-readable error reference from the canonical registry."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "resources" / "errors" / "error_registry.json"
OUTPUT_PATH = ROOT / "docs" / "ERROR_CODE_REFERENCE.md"


def _load(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def render() -> str:
    registry = _load(REGISTRY_PATH)
    zh = _load(ROOT / "resources" / "locales" / "zh_TW.json")
    en = _load(ROOT / "resources" / "locales" / "en_US.json")
    lines = [
        "# Error Code Reference",
        "",
        "> Generated by `scripts/generate_error_code_reference.py` from the canonical registry and locale catalogs. Do not edit the table manually.",
        "",
        "Error codes are stable machine identifiers and are never translated. Technical context is captured at runtime and is not duplicated here.",
        "",
        "| Code | Subsystem | Severity | zh-TW title | en-US title | Meaning | Recommended actions |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for code, definition in sorted(registry.items()):
        title_key = definition["title_key"]
        message_key = definition["message_key"]
        actions = "<br>".join(
            f"{index}. {_cell(en[key])} / {_cell(zh[key])}"
            for index, key in enumerate(definition["solution_keys"], start=1)
        )
        lines.append(
            "| {code} | {subsystem} | {severity} | {zh_title} | {en_title} | {meaning} | {actions} |".format(
                code=code,
                subsystem=definition["subsystem"],
                severity=definition["severity"],
                zh_title=_cell(zh[title_key]),
                en_title=_cell(en[title_key]),
                meaning=_cell(en[message_key]),
                actions=actions,
            )
        )
    lines.extend([
        "",
        "## Maintenance",
        "",
        "Change definitions in `resources/errors/error_registry.json`, change prose in both locale catalogs, run registry tests, then regenerate this file. Critical definitions may not expose Ignore or Continue actions.",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    OUTPUT_PATH.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
